/**
 * Brand → Model mappings for categories that have dynamic model fields
 * Used by DynamicCategoryForm to populate model dropdown based on brand selection
 */

// ── Car Models ──────────────────────────────────────────────────────
export const carModels: Record<string, { value: string; label: string }[]> = {
  toyota: [
    { value: "corolla", label: "كورولا" },
    { value: "camry", label: "كامري" },
    { value: "yaris", label: "ياريس" },
    { value: "rav4", label: "RAV4" },
    { value: "hilux", label: "هايلكس" },
    { value: "fortuner", label: "فورتشنر" },
    { value: "land_cruiser", label: "لاندكروزر" },
    { value: "rush", label: "راش" },
    { value: "avanza", label: "أفانزا" },
    { value: "belta", label: "بيلتا" },
    { value: "c_hr", label: "C-HR" },
    { value: "corolla_cross", label: "كورولا كروس" },
    { value: "other", label: "أخرى" },
  ],
  hyundai: [
    { value: "elantra", label: "إلنترا" },
    { value: "accent", label: "أكسنت" },
    { value: "tucson", label: "توسان" },
    { value: "creta", label: "كريتا" },
    { value: "verna", label: "فيرنا" },
    { value: "i10", label: "i10" },
    { value: "i20", label: "i20" },
    { value: "ix35", label: "ix35" },
    { value: "sonata", label: "سوناتا" },
    { value: "santa_fe", label: "سنتافي" },
    { value: "bayon", label: "بايون" },
    { value: "other", label: "أخرى" },
  ],
  chevrolet: [
    { value: "optra", label: "أوبترا" },
    { value: "lanos", label: "لانوس" },
    { value: "aveo", label: "أفيو" },
    { value: "cruze", label: "كروز" },
    { value: "captiva", label: "كابتيفا" },
    { value: "spark", label: "سبارك" },
    { value: "equinox", label: "إكوينوكس" },
    { value: "other", label: "أخرى" },
  ],
  nissan: [
    { value: "sunny", label: "صني" },
    { value: "sentra", label: "سنترا" },
    { value: "juke", label: "جوك" },
    { value: "qashqai", label: "قشقاي" },
    { value: "kicks", label: "كيكس" },
    { value: "x_trail", label: "إكس تريل" },
    { value: "tiida", label: "تيدا" },
    { value: "other", label: "أخرى" },
  ],
  kia: [
    { value: "cerato", label: "سيراتو" },
    { value: "sportage", label: "سبورتاج" },
    { value: "rio", label: "ريو" },
    { value: "picanto", label: "بيكانتو" },
    { value: "sorento", label: "سورينتو" },
    { value: "seltos", label: "سيلتوس" },
    { value: "k5", label: "K5" },
    { value: "soul", label: "سول" },
    { value: "carnival", label: "كارنيفال" },
    { value: "ev6", label: "EV6" },
    { value: "other", label: "أخرى" },
  ],
  bmw: [
    { value: "318i", label: "318i" },
    { value: "320i", label: "320i" },
    { value: "520i", label: "520i" },
    { value: "x1", label: "X1" },
    { value: "x3", label: "X3" },
    { value: "x5", label: "X5" },
    { value: "other", label: "أخرى" },
  ],
  mercedes: [
    { value: "c180", label: "C180" },
    { value: "c200", label: "C200" },
    { value: "e200", label: "E200" },
    { value: "e350", label: "E350" },
    { value: "gla", label: "GLA" },
    { value: "glc", label: "GLC" },
    { value: "s_class", label: "S-Class" },
    { value: "other", label: "أخرى" },
  ],
  fiat: [
    { value: "tipo", label: "تيبو" },
    { value: "punto", label: "بونتو" },
    { value: "500", label: "500" },
    { value: "128", label: "128" },
    { value: "shahin", label: "شاهين" },
    { value: "siena", label: "سيينا" },
    { value: "other", label: "أخرى" },
  ],
  skoda: [
    { value: "octavia", label: "أوكتافيا" },
    { value: "fabia", label: "فابيا" },
    { value: "superb", label: "سوبرب" },
    { value: "kodiaq", label: "كودياك" },
    { value: "kamiq", label: "كاميك" },
    { value: "rapid", label: "رابيد" },
    { value: "other", label: "أخرى" },
  ],
  opel: [
    { value: "corsa", label: "كورسا" },
    { value: "astra", label: "أسترا" },
    { value: "grandland", label: "جراندلاند" },
    { value: "other", label: "أخرى" },
  ],
  peugeot: [
    { value: "301", label: "301" },
    { value: "308", label: "308" },
    { value: "2008", label: "2008" },
    { value: "3008", label: "3008" },
    { value: "5008", label: "5008" },
    { value: "other", label: "أخرى" },
  ],
  renault: [
    { value: "logan", label: "لوجان" },
    { value: "sandero", label: "سانديرو" },
    { value: "megane", label: "ميجان" },
    { value: "duster", label: "داستر" },
    { value: "kadjar", label: "كادجار" },
    { value: "other", label: "أخرى" },
  ],
  suzuki: [
    { value: "swift", label: "سويفت" },
    { value: "dzire", label: "ديزاير" },
    { value: "vitara", label: "فيتارا" },
    { value: "ciaz", label: "سياز" },
    { value: "baleno", label: "بالينو" },
    { value: "ertiga", label: "إرتيجا" },
    { value: "other", label: "أخرى" },
  ],
  mitsubishi: [
    { value: "lancer", label: "لانسر" },
    { value: "attrage", label: "أتراج" },
    { value: "xpander", label: "إكسباندر" },
    { value: "eclipse_cross", label: "إكليبس كروس" },
    { value: "outlander", label: "آوتلاندر" },
    { value: "other", label: "أخرى" },
  ],
  honda: [
    { value: "civic", label: "سيفيك" },
    { value: "city", label: "سيتي" },
    { value: "accord", label: "أكورد" },
    { value: "cr_v", label: "CR-V" },
    { value: "hr_v", label: "HR-V" },
    { value: "other", label: "أخرى" },
  ],
  mg: [
    { value: "mg5", label: "MG5" },
    { value: "mg6", label: "MG6" },
    { value: "zs", label: "ZS" },
    { value: "rx5", label: "RX5" },
    { value: "hs", label: "HS" },
    { value: "mg4", label: "MG4" },
    { value: "other", label: "أخرى" },
  ],
  chery: [
    { value: "tiggo_4", label: "تيجو 4" },
    { value: "tiggo_7", label: "تيجو 7" },
    { value: "tiggo_8", label: "تيجو 8" },
    { value: "arrizo_5", label: "أريزو 5" },
    { value: "arrizo_6", label: "أريزو 6" },
    { value: "other", label: "أخرى" },
  ],
  byd: [
    { value: "f3", label: "F3" },
    { value: "seal", label: "سيل" },
    { value: "dolphin", label: "دولفين" },
    { value: "atto3", label: "Atto 3" },
    { value: "song_plus", label: "سونج بلس" },
    { value: "han", label: "هان" },
    { value: "other", label: "أخرى" },
  ],
  geely: [
    { value: "emgrand", label: "إمجراند" },
    { value: "coolray", label: "كولراي" },
    { value: "azkarra", label: "أزكارا" },
    { value: "starray", label: "ستاراي" },
    { value: "other", label: "أخرى" },
  ],
  other: [
    { value: "other", label: "أخرى" },
  ],
};

// ── Phone Models ────────────────────────────────────────────────────
export const phoneModels: Record<string, { value: string; label: string }[]> = {
  apple: [
    { value: "iphone_16_pro_max", label: "آيفون 16 برو ماكس" },
    { value: "iphone_16_pro", label: "آيفون 16 برو" },
    { value: "iphone_16_plus", label: "آيفون 16 بلس" },
    { value: "iphone_16", label: "آيفون 16" },
    { value: "iphone_15_pro_max", label: "آيفون 15 برو ماكس" },
    { value: "iphone_15_pro", label: "آيفون 15 برو" },
    { value: "iphone_15_plus", label: "آيفون 15 بلس" },
    { value: "iphone_15", label: "آيفون 15" },
    { value: "iphone_14_pro_max", label: "آيفون 14 برو ماكس" },
    { value: "iphone_14_pro", label: "آيفون 14 برو" },
    { value: "iphone_14_plus", label: "آيفون 14 بلس" },
    { value: "iphone_14", label: "آيفون 14" },
    { value: "iphone_13_pro_max", label: "آيفون 13 برو ماكس" },
    { value: "iphone_13_pro", label: "آيفون 13 برو" },
    { value: "iphone_13", label: "آيفون 13" },
    { value: "iphone_13_mini", label: "آيفون 13 ميني" },
    { value: "iphone_12_pro_max", label: "آيفون 12 برو ماكس" },
    { value: "iphone_12_pro", label: "آيفون 12 برو" },
    { value: "iphone_12", label: "آيفون 12" },
    { value: "iphone_12_mini", label: "آيفون 12 ميني" },
    { value: "iphone_11_pro_max", label: "آيفون 11 برو ماكس" },
    { value: "iphone_11_pro", label: "آيفون 11 برو" },
    { value: "iphone_11", label: "آيفون 11" },
    { value: "iphone_se", label: "آيفون SE" },
    { value: "iphone_xr", label: "آيفون XR" },
    { value: "iphone_xs", label: "آيفون XS" },
    { value: "iphone_x", label: "آيفون X" },
    { value: "ipad_pro", label: "آيباد برو" },
    { value: "ipad_air", label: "آيباد إير" },
    { value: "ipad", label: "آيباد" },
    { value: "ipad_mini", label: "آيباد ميني" },
    { value: "other", label: "أخرى" },
  ],
  samsung: [
    { value: "s24_ultra", label: "S24 Ultra" },
    { value: "s24_plus", label: "S24+" },
    { value: "s24", label: "S24" },
    { value: "s23_ultra", label: "S23 Ultra" },
    { value: "s23_plus", label: "S23+" },
    { value: "s23", label: "S23" },
    { value: "s22_ultra", label: "S22 Ultra" },
    { value: "s22_plus", label: "S22+" },
    { value: "s22", label: "S22" },
    { value: "s21", label: "S21" },
    { value: "z_fold_5", label: "Z Fold 5" },
    { value: "z_flip_5", label: "Z Flip 5" },
    { value: "a54", label: "A54" },
    { value: "a34", label: "A34" },
    { value: "a24", label: "A24" },
    { value: "a14", label: "A14" },
    { value: "a04", label: "A04" },
    { value: "m34", label: "M34" },
    { value: "m14", label: "M14" },
    { value: "tab_s9", label: "Tab S9" },
    { value: "tab_a9", label: "Tab A9" },
    { value: "other", label: "أخرى" },
  ],
  xiaomi: [
    { value: "14_ultra", label: "14 Ultra" },
    { value: "14_pro", label: "14 Pro" },
    { value: "14", label: "14" },
    { value: "13t_pro", label: "13T Pro" },
    { value: "13t", label: "13T" },
    { value: "redmi_note_13_pro", label: "Redmi Note 13 Pro" },
    { value: "redmi_note_13", label: "Redmi Note 13" },
    { value: "redmi_note_12_pro", label: "Redmi Note 12 Pro" },
    { value: "redmi_note_12", label: "Redmi Note 12" },
    { value: "redmi_13c", label: "Redmi 13C" },
    { value: "redmi_12", label: "Redmi 12" },
    { value: "poco_x6_pro", label: "Poco X6 Pro" },
    { value: "poco_x5", label: "Poco X5" },
    { value: "poco_m5", label: "Poco M5" },
    { value: "pad_6", label: "Pad 6" },
    { value: "other", label: "أخرى" },
  ],
  oppo: [
    { value: "reno_11_pro", label: "Reno 11 Pro" },
    { value: "reno_11", label: "Reno 11" },
    { value: "reno_10_pro", label: "Reno 10 Pro" },
    { value: "reno_10", label: "Reno 10" },
    { value: "a98", label: "A98" },
    { value: "a78", label: "A78" },
    { value: "a58", label: "A58" },
    { value: "a18", label: "A18" },
    { value: "find_x6_pro", label: "Find X6 Pro" },
    { value: "other", label: "أخرى" },
  ],
  realme: [
    { value: "gt5_pro", label: "GT5 Pro" },
    { value: "gt_neo5", label: "GT Neo 5" },
    { value: "11_pro_plus", label: "11 Pro+" },
    { value: "11_pro", label: "11 Pro" },
    { value: "c67", label: "C67" },
    { value: "c55", label: "C55" },
    { value: "c53", label: "C53" },
    { value: "c33", label: "C33" },
    { value: "narzo_60_pro", label: "Narzo 60 Pro" },
    { value: "other", label: "أخرى" },
  ],
  vivo: [
    { value: "v30_pro", label: "V30 Pro" },
    { value: "v30", label: "V30" },
    { value: "v29", label: "V29" },
    { value: "y100", label: "Y100" },
    { value: "y36", label: "Y36" },
    { value: "y27", label: "Y27" },
    { value: "y17s", label: "Y17s" },
    { value: "other", label: "أخرى" },
  ],
  huawei: [
    { value: "p60_pro", label: "P60 Pro" },
    { value: "p60", label: "P60" },
    { value: "mate_60_pro", label: "Mate 60 Pro" },
    { value: "nova_11_pro", label: "Nova 11 Pro" },
    { value: "nova_11", label: "Nova 11" },
    { value: "nova_y90", label: "Nova Y90" },
    { value: "nova_y70", label: "Nova Y70" },
    { value: "matepad", label: "MatePad" },
    { value: "other", label: "أخرى" },
  ],
  oneplus: [
    { value: "12", label: "12" },
    { value: "12r", label: "12R" },
    { value: "nord_3", label: "Nord 3" },
    { value: "nord_ce3", label: "Nord CE 3" },
    { value: "11", label: "11" },
    { value: "other", label: "أخرى" },
  ],
  nokia: [
    { value: "g42", label: "G42" },
    { value: "g22", label: "G22" },
    { value: "c32", label: "C32" },
    { value: "c22", label: "C22" },
    { value: "other", label: "أخرى" },
  ],
  other: [
    { value: "other", label: "أخرى" },
  ],
};

/**
 * Get model options for a given category and brand
 */
export function getModelOptions(
  categoryId: string,
  brandValue: string,
): { value: string; label: string }[] {
  if (categoryId === "cars") {
    return carModels[brandValue] || [{ value: "other", label: "أخرى" }];
  }
  if (categoryId === "phones") {
    return phoneModels[brandValue] || [{ value: "other", label: "أخرى" }];
  }
  return [];
}
