import type { CategoryConfig } from "@/types";

export const categoriesConfig: CategoryConfig[] = [
  {
    id: "cars",
    name: "السيارات",
    icon: "🚗",
    slug: "cars",
    subcategories: [
      { id: "passenger", name: "سيارات ملاكي", slug: "passenger" },
      { id: "microbus", name: "ميكروباص", slug: "microbus" },
      { id: "trucks", name: "نقل", slug: "trucks" },
      { id: "motorcycles", name: "موتوسيكلات", slug: "motorcycles" },
      { id: "car-parts", name: "قطع غيار", slug: "car-parts" },
    ],
    fields: [
      { id: "brand", label: "الماركة", type: "select", isRequired: true, order: 1, options: [
        { value: "toyota", label: "تويوتا" }, { value: "hyundai", label: "هيونداي" },
        { value: "chevrolet", label: "شيفروليه" }, { value: "nissan", label: "نيسان" },
        { value: "kia", label: "كيا" }, { value: "bmw", label: "بي إم دبليو" },
        { value: "mercedes", label: "مرسيدس" }, { value: "fiat", label: "فيات" },
        { value: "skoda", label: "سكودا" }, { value: "opel", label: "أوبل" },
        { value: "peugeot", label: "بيجو" }, { value: "renault", label: "رينو" },
        { value: "suzuki", label: "سوزوكي" }, { value: "mitsubishi", label: "ميتسوبيشي" },
        { value: "honda", label: "هوندا" }, { value: "mg", label: "MG" },
        { value: "chery", label: "شيري" }, { value: "byd", label: "بي واي دي" },
        { value: "geely", label: "جيلي" }, { value: "other", label: "أخرى" },
      ]},
      { id: "model", label: "الموديل", type: "select", isRequired: true, order: 2, options: [] },
      { id: "year", label: "السنة", type: "year-picker", isRequired: true, order: 3 },
      { id: "mileage", label: "الكيلومتراج", type: "number", unit: "كم", isRequired: true, order: 4 },
      { id: "color", label: "اللون", type: "select", isRequired: false, order: 5, options: [
        { value: "white", label: "أبيض" }, { value: "black", label: "أسود" },
        { value: "silver", label: "فضي" }, { value: "red", label: "أحمر" },
        { value: "blue", label: "أزرق" }, { value: "gray", label: "رمادي" },
        { value: "gold", label: "ذهبي" }, { value: "other", label: "أخرى" },
      ]},
      { id: "fuel", label: "نوع الوقود", type: "select", isRequired: false, order: 6, options: [
        { value: "petrol", label: "بنزين" }, { value: "diesel", label: "سولار" },
        { value: "gas", label: "غاز" }, { value: "electric", label: "كهرباء" },
        { value: "hybrid", label: "هايبرد" },
      ]},
      { id: "transmission", label: "ناقل الحركة", type: "select", isRequired: false, order: 7, options: [
        { value: "automatic", label: "أوتوماتيك" }, { value: "manual", label: "مانيوال" },
      ]},
      { id: "engine_cc", label: "سعة المحرك", type: "select", isRequired: false, order: 8, options: [
        { value: "1000", label: "1000" }, { value: "1200", label: "1200" },
        { value: "1300", label: "1300" }, { value: "1500", label: "1500" },
        { value: "1600", label: "1600" }, { value: "1800", label: "1800" },
        { value: "2000", label: "2000" }, { value: "2500", label: "2500" },
        { value: "3000+", label: "3000+" },
      ]},
      { id: "condition", label: "الحالة", type: "select", isRequired: false, order: 9, options: [
        { value: "new", label: "جديدة" }, { value: "used", label: "مستعملة" },
        { value: "accident", label: "حادثة" },
      ]},
      { id: "licensed", label: "مُرخصة", type: "toggle", isRequired: false, order: 10 },
    ],
    requiredFields: ["brand", "model", "year", "mileage"],
    titleTemplate: "${brand} ${model} ${year} — ${mileage} كم",
    descriptionTemplate: "سيارة ${brand} ${model} موديل ${year}، مسافة ${mileage} كم",
  },
  {
    id: "real_estate",
    name: "العقارات",
    icon: "🏠",
    slug: "real-estate",
    subcategories: [
      { id: "apartments-sale", name: "شقق للبيع", slug: "apartments-sale" },
      { id: "apartments-rent", name: "شقق للإيجار", slug: "apartments-rent" },
      { id: "villas", name: "فيلات", slug: "villas" },
      { id: "land", name: "أراضي", slug: "land" },
      { id: "commercial", name: "محلات تجارية", slug: "commercial" },
      { id: "offices", name: "مكاتب", slug: "offices" },
    ],
    fields: [
      { id: "property_type", label: "النوع", type: "select", isRequired: true, order: 1, options: [
        { value: "apartment", label: "شقة" }, { value: "villa", label: "فيلا" },
        { value: "land", label: "أرض" }, { value: "shop", label: "محل" },
        { value: "office", label: "مكتب" }, { value: "duplex", label: "دوبلكس" },
        { value: "penthouse", label: "بنتهاوس" }, { value: "studio", label: "استوديو" },
      ]},
      { id: "area", label: "المساحة", type: "number", unit: "م²", isRequired: true, order: 2 },
      { id: "rooms", label: "عدد الغرف", type: "select", isRequired: true, order: 3, options: [
        { value: "1", label: "1" }, { value: "2", label: "2" }, { value: "3", label: "3" },
        { value: "4", label: "4" }, { value: "5+", label: "5+" },
      ]},
      { id: "floor", label: "الطابق", type: "select", isRequired: true, order: 4, options: [
        { value: "basement", label: "بدروم" }, { value: "ground", label: "أرضي" },
        ...Array.from({ length: 20 }, (_, i) => ({ value: `${i + 1}`, label: `${i + 1}` })),
        { value: "last", label: "أخير" },
      ]},
      { id: "bathrooms", label: "عدد الحمامات", type: "select", isRequired: false, order: 5, options: [
        { value: "1", label: "1" }, { value: "2", label: "2" },
        { value: "3", label: "3" }, { value: "4+", label: "4+" },
      ]},
      { id: "finishing", label: "التشطيب", type: "select", isRequired: false, order: 6, options: [
        { value: "super_lux", label: "سوبر لوكس" }, { value: "lux", label: "لوكس" },
        { value: "semi", label: "نص تشطيب" }, { value: "plastered", label: "على المحارة" },
        { value: "bricks", label: "على الطوب" },
      ]},
      { id: "elevator", label: "أسانسير", type: "toggle", isRequired: false, order: 7 },
      { id: "garage", label: "جراج", type: "toggle", isRequired: false, order: 8 },
      { id: "garden", label: "حديقة", type: "toggle", isRequired: false, order: 9 },
      { id: "furnished", label: "مفروشة", type: "toggle", isRequired: false, order: 10 },
    ],
    requiredFields: ["property_type", "area", "rooms", "floor"],
    titleTemplate: "${property_type} ${area}م² — ${rooms} غرف — الطابق ${floor}",
    descriptionTemplate: "${property_type} مساحة ${area} متر مربع، ${rooms} غرف",
  },
  {
    id: "phones",
    name: "الموبايلات والتابلت",
    icon: "📱",
    slug: "phones",
    subcategories: [
      { id: "mobile", name: "موبايلات", slug: "mobile" },
      { id: "tablet", name: "تابلت", slug: "tablet" },
      { id: "phone-accessories", name: "إكسسوارات", slug: "phone-accessories" },
      { id: "phone-parts", name: "قطع غيار", slug: "phone-parts" },
    ],
    fields: [
      { id: "brand", label: "الماركة", type: "select", isRequired: true, order: 1, options: [
        { value: "apple", label: "آيفون" }, { value: "samsung", label: "سامسونج" },
        { value: "xiaomi", label: "شاومي" }, { value: "oppo", label: "أوبو" },
        { value: "realme", label: "ريلمي" }, { value: "vivo", label: "فيفو" },
        { value: "huawei", label: "هواوي" }, { value: "oneplus", label: "ون بلس" },
        { value: "nokia", label: "نوكيا" }, { value: "other", label: "أخرى" },
      ]},
      { id: "model", label: "الموديل", type: "select", isRequired: true, order: 2, options: [] },
      { id: "storage", label: "المساحة", type: "select", isRequired: true, order: 3, options: [
        { value: "32", label: "32GB" }, { value: "64", label: "64GB" },
        { value: "128", label: "128GB" }, { value: "256", label: "256GB" },
        { value: "512", label: "512GB" }, { value: "1024", label: "1TB" },
      ]},
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 4, options: [
        { value: "sealed", label: "جديد متبرشم" }, { value: "like_new", label: "مستعمل زيرو" },
        { value: "good", label: "مستعمل كويس" }, { value: "fair", label: "مستعمل مقبول" },
        { value: "broken", label: "تالف" },
      ]},
      { id: "color", label: "اللون", type: "select", isRequired: false, order: 5, options: [
        { value: "black", label: "أسود" }, { value: "white", label: "أبيض" },
        { value: "blue", label: "أزرق" }, { value: "gold", label: "ذهبي" },
        { value: "other", label: "أخرى" },
      ]},
      { id: "ram", label: "الرام", type: "select", isRequired: false, order: 6, options: [
        { value: "3", label: "3GB" }, { value: "4", label: "4GB" },
        { value: "6", label: "6GB" }, { value: "8", label: "8GB" },
        { value: "12", label: "12GB" }, { value: "16", label: "16GB" },
      ]},
      { id: "battery", label: "البطارية", type: "select", isRequired: false, order: 7, options: [
        { value: "excellent", label: "ممتازة" }, { value: "good", label: "جيدة" },
        { value: "fair", label: "مقبولة" },
      ]},
      { id: "with_box", label: "مع العلبة", type: "toggle", isRequired: false, order: 8 },
      { id: "with_warranty", label: "مع الضمان", type: "toggle", isRequired: false, order: 9 },
    ],
    requiredFields: ["brand", "model", "storage", "condition"],
    titleTemplate: "${brand} ${model} — ${storage} — ${condition}",
    descriptionTemplate: "${brand} ${model} مساحة ${storage}، حالة: ${condition}",
  },
  {
    id: "fashion",
    name: "الموضة",
    icon: "👗",
    slug: "fashion",
    subcategories: [
      { id: "men", name: "ملابس رجالي", slug: "men" },
      { id: "women", name: "ملابس حريمي", slug: "women" },
      { id: "kids", name: "ملابس أطفال", slug: "kids" },
      { id: "shoes", name: "أحذية", slug: "shoes" },
      { id: "bags", name: "شنط", slug: "bags" },
      { id: "fashion-accessories", name: "إكسسوارات", slug: "fashion-accessories" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "text", isRequired: true, order: 1 },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 2, options: [
        { value: "new_tagged", label: "جديد بالتاج" }, { value: "new_untagged", label: "جديد بدون تاج" },
        { value: "excellent", label: "مستعمل ممتاز" }, { value: "good", label: "مستعمل جيد" },
      ]},
      { id: "size", label: "المقاس", type: "select", isRequired: true, order: 3, options: [
        { value: "xs", label: "XS" }, { value: "s", label: "S" }, { value: "m", label: "M" },
        { value: "l", label: "L" }, { value: "xl", label: "XL" }, { value: "xxl", label: "XXL" },
      ]},
      { id: "brand", label: "الماركة", type: "text", isRequired: true, order: 4, placeholder: "اسم الماركة" },
      { id: "color", label: "اللون", type: "select", isRequired: false, order: 5, options: [
        { value: "black", label: "أسود" }, { value: "white", label: "أبيض" },
        { value: "blue", label: "أزرق" }, { value: "red", label: "أحمر" },
        { value: "other", label: "أخرى" },
      ]},
      { id: "material", label: "الخامة", type: "select", isRequired: false, order: 6, options: [
        { value: "cotton", label: "قطن" }, { value: "polyester", label: "بوليستر" },
        { value: "leather", label: "جلد" }, { value: "jeans", label: "جينز" },
        { value: "silk", label: "حرير" }, { value: "linen", label: "كتان" },
      ]},
    ],
    requiredFields: ["type", "condition", "size", "brand"],
    titleTemplate: "${type} ${brand} — مقاس ${size} — ${condition}",
    descriptionTemplate: "${type} ماركة ${brand}، مقاس ${size}، ${condition}",
  },
  {
    id: "scrap",
    name: "الخردة",
    icon: "♻️",
    slug: "scrap",
    subcategories: [
      { id: "iron", name: "حديد", slug: "iron" },
      { id: "aluminum", name: "ألومنيوم", slug: "aluminum" },
      { id: "copper", name: "نحاس", slug: "copper" },
      { id: "plastic", name: "بلاستيك", slug: "plastic" },
      { id: "paper", name: "ورق", slug: "paper" },
      { id: "old-devices", name: "أجهزة قديمة", slug: "old-devices" },
      { id: "construction", name: "مخلفات بناء", slug: "construction" },
      { id: "scrap-other", name: "أخرى", slug: "scrap-other" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "select", isRequired: true, order: 1, options: [] },
      { id: "weight", label: "الوزن التقريبي", type: "number", unit: "كجم", isRequired: true, order: 2 },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 3, options: [
        { value: "clean", label: "نظيف" }, { value: "mixed", label: "مختلط" },
        { value: "needs_sorting", label: "يحتاج فرز" },
      ]},
      { id: "quantity", label: "الكمية", type: "text", isRequired: false, order: 4 },
    ],
    requiredFields: ["type", "weight", "condition"],
    titleTemplate: "${type} خردة — ${weight} كجم — ${condition}",
    descriptionTemplate: "${type} خردة وزن ${weight} كجم، ${condition}",
  },
  {
    id: "gold",
    name: "الذهب والفضة",
    icon: "💰",
    slug: "gold",
    subcategories: [
      { id: "gold-items", name: "ذهب", slug: "gold-items" },
      { id: "silver", name: "فضة", slug: "silver" },
      { id: "diamond", name: "ألماس", slug: "diamond" },
      { id: "precious-watches", name: "ساعات ثمينة", slug: "precious-watches" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "select", isRequired: true, order: 1, options: [
        { value: "ring", label: "خاتم" }, { value: "chain", label: "سلسلة" },
        { value: "earring", label: "حلق" }, { value: "bracelet", label: "أسورة" },
        { value: "necklace", label: "عقد" }, { value: "wedding_ring", label: "دبلة" },
        { value: "engagement_ring", label: "محبس" }, { value: "gold_coin", label: "جنيه ذهب" },
        { value: "bar", label: "سبيكة" }, { value: "other", label: "أخرى" },
      ]},
      { id: "karat", label: "العيار", type: "select", isRequired: true, order: 2, options: [
        { value: "24", label: "عيار 24" }, { value: "21", label: "عيار 21" },
        { value: "18", label: "عيار 18" }, { value: "14", label: "عيار 14" },
        { value: "silver_925", label: "فضة 925" }, { value: "silver_900", label: "فضة 900" },
      ]},
      { id: "weight", label: "الوزن", type: "number", unit: "جرام", isRequired: true, order: 3 },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 4, options: [
        { value: "new", label: "جديد" }, { value: "used", label: "مستعمل" },
      ]},
      { id: "has_gemstone", label: "يوجد فص/حجر", type: "toggle", isRequired: false, order: 5 },
      { id: "certificate", label: "شهادة", type: "toggle", isRequired: false, order: 6 },
    ],
    requiredFields: ["type", "karat", "weight", "condition"],
    titleTemplate: "${type} ذهب ${karat} — ${weight} جرام — ${condition}",
    descriptionTemplate: "${type} ${karat}، وزن ${weight} جرام، ${condition}",
  },
  {
    id: "luxury",
    name: "السلع الفاخرة",
    icon: "💎",
    slug: "luxury",
    subcategories: [
      { id: "luxury-bags", name: "شنط فاخرة", slug: "luxury-bags" },
      { id: "sunglasses", name: "نظارات", slug: "sunglasses" },
      { id: "watches", name: "ساعات", slug: "watches" },
      { id: "perfumes", name: "عطور", slug: "perfumes" },
      { id: "pens", name: "أقلام", slug: "pens" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "select", isRequired: true, order: 1, options: [] },
      { id: "brand", label: "الماركة", type: "select", isRequired: true, order: 2, options: [
        { value: "louis_vuitton", label: "Louis Vuitton" }, { value: "gucci", label: "Gucci" },
        { value: "chanel", label: "Chanel" }, { value: "rolex", label: "Rolex" },
        { value: "cartier", label: "Cartier" }, { value: "dior", label: "Dior" },
        { value: "prada", label: "Prada" }, { value: "other", label: "أخرى" },
      ]},
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 3, options: [
        { value: "sealed", label: "جديد متبرشم" }, { value: "new_unused", label: "جديد بدون استعمال" },
        { value: "excellent", label: "مستعمل ممتاز" }, { value: "good", label: "مستعمل جيد" },
      ]},
      { id: "authentic", label: "أصلي/تقليد", type: "select", isRequired: true, order: 4, options: [
        { value: "authentic_warranty", label: "أصلي بالضمان" }, { value: "authentic_no_warranty", label: "أصلي بدون ضمان" },
        { value: "high_copy", label: "هاي كوبي" }, { value: "copy", label: "كوبي" },
      ]},
      { id: "purchase_year", label: "سنة الشراء", type: "year-picker", isRequired: false, order: 5 },
      { id: "with_box", label: "مع العلبة", type: "toggle", isRequired: false, order: 6 },
      { id: "with_receipt", label: "مع الفاتورة", type: "toggle", isRequired: false, order: 7 },
    ],
    requiredFields: ["type", "brand", "condition", "authentic"],
    titleTemplate: "${type} ${brand} — ${authentic} — ${condition}",
    descriptionTemplate: "${type} ${brand}، ${condition}، ${authentic}",
  },
  {
    id: "appliances",
    name: "الأجهزة المنزلية",
    icon: "🏠",
    slug: "appliances",
    subcategories: [
      { id: "washers", name: "غسالات", slug: "washers" },
      { id: "fridges", name: "ثلاجات", slug: "fridges" },
      { id: "cookers", name: "بوتاجازات", slug: "cookers" },
      { id: "ac", name: "مكيفات", slug: "ac" },
      { id: "heaters", name: "سخانات", slug: "heaters" },
      { id: "small-appliances", name: "أجهزة صغيرة", slug: "small-appliances" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "select", isRequired: true, order: 1, options: [] },
      { id: "brand", label: "الماركة", type: "select", isRequired: true, order: 2, options: [
        { value: "toshiba", label: "توشيبا" }, { value: "sharp", label: "شارب" },
        { value: "samsung", label: "سامسونج" }, { value: "lg", label: "إل جي" },
        { value: "beko", label: "بيكو" }, { value: "universal", label: "يونيفرسال" },
        { value: "carrier", label: "كاريير" }, { value: "fresh", label: "فريش" },
        { value: "other", label: "أخرى" },
      ]},
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 3, options: [
        { value: "sealed", label: "جديد متبرشم" }, { value: "excellent", label: "مستعمل ممتاز" },
        { value: "good", label: "مستعمل كويس" }, { value: "needs_repair", label: "يحتاج صيانة" },
      ]},
      { id: "purchase_year", label: "سنة الشراء", type: "year-picker", isRequired: true, order: 4 },
      { id: "capacity", label: "السعة", type: "text", isRequired: false, order: 5 },
      { id: "warranty", label: "الضمان", type: "toggle", isRequired: false, order: 6 },
    ],
    requiredFields: ["type", "brand", "condition", "purchase_year"],
    titleTemplate: "${type} ${brand} — ${purchase_year} — ${condition}",
    descriptionTemplate: "${type} ${brand} موديل ${purchase_year}، ${condition}",
  },
  {
    id: "furniture",
    name: "الأثاث والديكور",
    icon: "🪑",
    slug: "furniture",
    subcategories: [
      { id: "bedroom", name: "غرف نوم", slug: "bedroom" },
      { id: "dining", name: "سفرة", slug: "dining" },
      { id: "living", name: "أنتريه", slug: "living" },
      { id: "kitchen", name: "مطابخ", slug: "kitchen" },
      { id: "decor", name: "ديكورات", slug: "decor" },
      { id: "lighting", name: "إضاءة", slug: "lighting" },
      { id: "carpets", name: "سجاد", slug: "carpets" },
      { id: "furniture-other", name: "أخرى", slug: "furniture-other" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "select", isRequired: true, order: 1, options: [] },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 2, options: [
        { value: "new", label: "جديد" }, { value: "excellent", label: "مستعمل ممتاز" },
        { value: "good", label: "مستعمل جيد" }, { value: "needs_renewal", label: "يحتاج تجديد" },
      ]},
      { id: "material", label: "الخامة", type: "select", isRequired: true, order: 3, options: [
        { value: "beech", label: "خشب زان" }, { value: "oak", label: "خشب أرو" },
        { value: "mdf", label: "MDF" }, { value: "pine", label: "خشب موسكي" },
        { value: "metal", label: "معدن" }, { value: "other", label: "أخرى" },
      ]},
      { id: "color", label: "اللون", type: "select", isRequired: false, order: 4, options: [
        { value: "brown", label: "بني" }, { value: "white", label: "أبيض" },
        { value: "black", label: "أسود" }, { value: "other", label: "أخرى" },
      ]},
      { id: "pieces", label: "عدد القطع", type: "number", isRequired: false, order: 5 },
      { id: "dimensions", label: "الأبعاد", type: "text", isRequired: false, order: 6 },
    ],
    requiredFields: ["type", "condition", "material"],
    titleTemplate: "${type} ${material} — ${condition}",
    descriptionTemplate: "${type} ${material}، ${condition}",
  },
  {
    id: "hobbies",
    name: "الهوايات",
    icon: "🎮",
    slug: "hobbies",
    subcategories: [
      { id: "music", name: "آلات موسيقية", slug: "music" },
      { id: "sports", name: "معدات رياضية", slug: "sports" },
      { id: "gaming", name: "ألعاب فيديو", slug: "gaming" },
      { id: "books", name: "كتب", slug: "books" },
      { id: "cameras", name: "كاميرات", slug: "cameras" },
      { id: "bikes", name: "دراجات", slug: "bikes" },
      { id: "antiques", name: "تحف وأنتيكات", slug: "antiques" },
      { id: "pets", name: "حيوانات أليفة", slug: "pets" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "text", isRequired: true, order: 1 },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 2, options: [
        { value: "new", label: "جديد" }, { value: "excellent", label: "مستعمل ممتاز" },
        { value: "good", label: "مستعمل جيد" }, { value: "fair", label: "مستعمل مقبول" },
      ]},
      { id: "brand", label: "الماركة/الوصف", type: "text", isRequired: true, order: 3 },
      { id: "purchase_year", label: "سنة الشراء", type: "year-picker", isRequired: false, order: 4 },
      { id: "with_accessories", label: "مع ملحقات", type: "toggle", isRequired: false, order: 5 },
    ],
    requiredFields: ["type", "condition", "brand"],
    titleTemplate: "${brand} ${type} — ${condition}",
    descriptionTemplate: "${type} ${brand}، ${condition}",
  },
  {
    id: "tools",
    name: "العدد والأدوات",
    icon: "🔧",
    slug: "tools",
    subcategories: [
      { id: "hand-tools", name: "عدد يدوية", slug: "hand-tools" },
      { id: "power-tools", name: "عدد كهربائية", slug: "power-tools" },
      { id: "workshop", name: "معدات ورش", slug: "workshop" },
      { id: "agricultural", name: "معدات زراعية", slug: "agricultural" },
      { id: "restaurant-equipment", name: "معدات مطاعم", slug: "restaurant-equipment" },
    ],
    fields: [
      { id: "type", label: "النوع", type: "text", isRequired: true, order: 1 },
      { id: "condition", label: "الحالة", type: "select", isRequired: true, order: 2, options: [
        { value: "new", label: "جديد" }, { value: "working", label: "مستعمل يعمل" },
        { value: "needs_repair", label: "يحتاج صيانة" },
      ]},
      { id: "brand", label: "الماركة", type: "text", isRequired: true, order: 3 },
      { id: "quantity", label: "الكمية", type: "number", isRequired: false, order: 4 },
      { id: "power", label: "مصدر الطاقة", type: "select", isRequired: false, order: 5, options: [
        { value: "electric", label: "كهرباء" }, { value: "battery", label: "بطارية" },
        { value: "manual", label: "يدوي" }, { value: "petrol", label: "بنزين" },
      ]},
    ],
    requiredFields: ["type", "condition", "brand"],
    titleTemplate: "${type} ${brand} — ${condition}",
    descriptionTemplate: "${type} ${brand}، ${condition}",
  },
  {
    id: "services",
    name: "الخدمات",
    icon: "🛠️",
    slug: "services",
    subcategories: [
      { id: "plumbing", name: "سباكة", slug: "plumbing" },
      { id: "electrical", name: "كهرباء", slug: "electrical" },
      { id: "painting", name: "نقاشة", slug: "painting" },
      { id: "carpentry", name: "نجارة", slug: "carpentry" },
      { id: "device-repair", name: "صيانة أجهزة", slug: "device-repair" },
      { id: "moving", name: "نقل أثاث", slug: "moving" },
      { id: "cleaning", name: "تنظيف", slug: "cleaning" },
      { id: "tech", name: "خدمات تقنية", slug: "tech" },
      { id: "tutoring", name: "دروس خصوصية", slug: "tutoring" },
      { id: "services-other", name: "خدمات أخرى", slug: "services-other" },
    ],
    fields: [
      { id: "service_type", label: "نوع الخدمة", type: "select", isRequired: true, order: 1, options: [] },
      { id: "pricing", label: "التسعير", type: "select", isRequired: true, order: 2, options: [
        { value: "hourly", label: "بالساعة" }, { value: "project", label: "بالمشروع" },
        { value: "negotiable", label: "بالاتفاق" }, { value: "fixed", label: "سعر ثابت" },
      ]},
      { id: "experience", label: "الخبرة", type: "select", isRequired: true, order: 3, options: [
        { value: "less_1", label: "أقل من سنة" }, { value: "1_3", label: "1-3 سنوات" },
        { value: "3_5", label: "3-5 سنوات" }, { value: "5_plus", label: "أكثر من 5 سنوات" },
      ]},
      { id: "working_days", label: "أيام العمل", type: "multi-select", isRequired: false, order: 4, options: [
        { value: "sat", label: "السبت" }, { value: "sun", label: "الأحد" },
        { value: "mon", label: "الاثنين" }, { value: "tue", label: "الثلاثاء" },
        { value: "wed", label: "الأربعاء" }, { value: "thu", label: "الخميس" },
        { value: "fri", label: "الجمعة" },
      ]},
      { id: "working_hours", label: "مواعيد العمل", type: "text", isRequired: false, order: 5 },
    ],
    requiredFields: ["service_type", "pricing", "experience"],
    titleTemplate: "${service_type} — خبرة ${experience} — ${pricing}",
    descriptionTemplate: "${service_type}، خبرة ${experience}، ${pricing}",
  },
];

export function getCategoryBySlug(slug: string): CategoryConfig | undefined {
  return categoriesConfig.find((c) => c.slug === slug);
}

export function getCategoryById(id: string): CategoryConfig | undefined {
  return categoriesConfig.find((c) => c.id === id);
}
